import { type NextPage } from "next";
import Head from "next/head";
import { signIn, useSession } from "next-auth/react";
import Timeline from "../components/Timeline";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {!session && (
          <div className="flex h-screen flex-col items-center justify-center text-gray-700">
            <div className="flex h-[300px] w-[500px] flex-col items-center justify-center rounded-xl bg-white shadow-xl">
              <p className="p-4 text-2xl font-bold">
                Bienvenu sur la page de mon projet!
              </p>
              <p className="p-4">Avez vous un compte Discord?</p>
              <button
                onClick={() => signIn()}
                className="focus:shadow-outline rounded bg-blue-500 py-2 px-4 font-bold text-white hover:bg-blue-700 focus:outline-none"
              >
                Se connecter
              </button>
            </div>
          </div>
        )}
        {session && <Timeline />}
      </div>
    </>
  );
};

export default Home;
